const CONSTANT = {
  SERVERNOTFOUND: "ENOTFOUND",
  SERVERERRORMESSAGE: "Internal Server Error",
  ERRORMESSAGE: "Data not found",
  RESPONSE_CODE_START_RANGE: 404,
  RESPONSE_CODE_END_RANGE: 499,
  DATA_NOT_FOUND: 404,
  SLOT_ERROR: 417,
  PAGINATION_LIMIT: 30
};

module.exports = CONSTANT;
